name: Kicad

on:
  push:
    paths:
      - "**.kicad_sch"
      - "**.kicad_pcb"
      - "**.kicad_mod"
      - "**.lib"
      - "**.yaml"
  pull_request:
    paths:
      - "**.kicad_sch"
      - "**.kicad_pcb"
      - "**.kicad_mod"
      - "**.lib"
      - "**.yaml"

jobs:
  Kicad:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: INTI-CMNB/KiBot@v2_k6
        with:
          # Required - kibot config file
          config: kicad-example/config.kibot.yaml
          # optional - prefix to output defined in config
          dir: output
          # Required for v6
          schema: "kicad-example/kicad-example.kicad_sch"
          # optional - PCB design file
          board: "kicad-example/kicad-example.kicad_pcb"
      - name: upload results
        uses: actions/upload-artifact@v2
        with:
          name: output
          path: output
